replicaCount: 1

image:
  repository: your-docker-repo/fastapi-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  nodePort: 30007  # NodePort you want to expose

ingress:
  enabled: false

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}

mongodb:
  enabled: true
  image: mongo:5.5
  port: 27017
  host: mongo

env:
  - name: MONGODB_HOST
    value: mongo


