api:
  replicaCount: 1
  image:
    repository: 
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30101
  mongodb:
    host: mongodb
    port: 27017
    database: vdt2024

mongodb:
  replicaCount: 1
  image:
    repository: mongo
    tag: "5.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  persistence:
    enabled: false
    size: 1Gi
