api:
  replicaCount: 2
  image:
    repository: jasmine150720/vdt2024-fastapi
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30101

mongodb:
  username: YWRtaW4=
  password: YWRtaW4=

