api:
  replicaCount: 2
  image:
    repository: jasmine150720/vdt2024-fastapi
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30100

database:
  replicaCount: 1
  image:
    repository: mongo
    tag: "5.0"
    pullPolicy: IfNotPresent

mongodb:
  username: YWRtaW4=
  password: YWRtaW4=
  database: admin

persistence:
  enabled: true
  storageClassName: standard
  accessMode: ReadWriteOnce
  size: 1Gi
