replicaCount: 1

servicename: api

environment: 'kubernetes'


api:
  image:
    repository: jasmine150720/vdt2024-fastapi
    pullPolicy: Always
    tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "vdt2024-api"

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  portFrontend: 3000
  portAPI: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - hostsAPI: api.schoolapp.com
      hostsFrontend: app.schoolapp.com
  tls:
    - secretNameAPI: api-schoolapp-tls
      secretNameFrontend: frontend-schoolapp-tls
      hostsAPI:
        - api.schoolapp.com
      hostsFrontend:
        - app.schoolapp.com
