replicaCount: 1

fastapi:
  image:
    repository: jasmine150720/vdt2024-fastapi
  service:
    type: NodePort
    port: 80
    nodePort: 31049

mongo:
  image:
    repository: mongo
    tag: 5.0
  service:
    type: NodePort
    port: 27017
    nodePort: 31048
  persistence:
    storage: 500Mi
    storageClassName: manual
    accessModes:
      - ReadWriteOnce
    hostPath: /mnt/data
