replicaCount: 1

image:
  repository: jasmine150720/vdt2024-react
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30007  

mongodb:
  image: mongo:5.0
  port: 27017

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: your-app.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []



